name: Naukri Automation

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 1:30 AM UTC (7:00 AM IST)
  workflow_dispatch:

jobs:
  naukri-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Chrome and Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      - name: Start Virtual Display
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Set DISPLAY Environment Variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
